### ISSUE TITLE
placement: 'left' doesn't work

### ISSUE THREAD

**Issue by spencerisgabba** [noxxxxxxxx/drawer#2]
I cant align the drawer to the left

export default {
  data() {
    return {
      visible: false
    };
  },
  props: {
    placement: "left"
  },
  methods: {
    open() {
      this.visible = true;
    },

    close() {
      this.visible = false;
    }
  }
};
</script>

**Comment by noxxxxxxxx** [comment]
All you need to do is write like this:
` <vue-drawer
      :visible.sync="visible"
      placement="left">
</vue-drawer>
`
